version: "3.7"
services:
  light_db:
    image: "postgres:11.2-alpine"
    container_name: "light-test"
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=smart_lights
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s

  flyway:
    image: "flyway/flyway:9.16-alpine"
    container_name: "flyway-light"
    command: -url=jdbc:postgresql://light_db:5432/smart_lights -user=postgres -password=password -connectRetries=20 migrate
    volumes:
      - ./sql/migrations:/flyway/sql
    depends_on:
    - light_db